name: Testing with PyTest

on:
  push:
    branches:
      - 'main'
  pull_request:
    types:
      - opened
      - ready_for_review
    branches:
      - 'main'


jobs:
  test:
    strategy:
      matrix:
        python-version: [3.8.*]
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Switch to Current Branch
        run: git checkout ${{ env.BRANCH }}

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup PIP Cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip -U
          pip install -r requirements.dev.txt

      - name: Run unit tests
        run: python -m pytest --import-mode=append tests/
